runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /_ah/push-handlers/.*
  script: main.app
  login: admin
  
libraries:
- name: flask
  version: "0.12"

#[START env]
env_variables:
    PUBSUB_TOPIC: your-topic
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: 1234abc
#[END env]
